
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yebsxzaqnludaaaigrxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllYnN4emFxbmx1ZGFhYWlncnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MDg0NzIsImV4cCI6MjA2Mjk4NDQ3Mn0.S-NHda90IlG2Gj4ogJz5r5Uuv03us2f1Mshc4Hl158Y";

// Direct database connection string using Transaction pooler
// Replace [YOUR-PASSWORD] with the actual password
const DB_CONNECTION_STRING = "postgresql://postgres.yebsxzaqnludaaaigrxm:WarungMadura2025@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public',
  },
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Export the connection string for any direct PostgreSQL connections if needed
export const dbConnectionString = DB_CONNECTION_STRING;
